modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/shizotoaster/mc-ui-input-undo/issues"
license = "GPL v3"

[[mods]]
modId = "uiinputundo"
version = "${version}"
displayName = "UI Input Undo (Redo)"
authors = "thecsdev, shizotoaster"
description = '''
A client-side Minecraft mod that allows you to undo and redo text in UI input fields.
'''
logoFile = "uiinputundo.png"
displayURL = "https://modrinth.com/mod/uiinputundo"

[[dependencies.uiinputundo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"